name: Build and push Container

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3
      - uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3
      - uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5
        id: meta
        with:
          images: |
            ${{ github.repository }}
            ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value={{sha}}
            type=raw,value=latest,enable={{is_default_branch}}

      
      - uses: docker/login-action@v3.4.0
        name: login to Azure Container Registry
        with:
          registry: crdnsfprdfrc001.azurecr.io
          username: ${{ vars.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}
      
      - uses: docker/build-push-action@v6.15.0
        name: Build and push Docker images
        with:
          context: ./src
          annotations: ${{ steps.meta.outputs.annotations }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name == 'push' }}
          tags: |
            crdnsfprdfrc001.azurecr.io/az-dns-forwarder:latest
            crdnsfprdfrc001.azurecr.io/az-dns-forwarder:${{ github.sha }}
